title: Aksha Hrudhai # your name (or website title) here
logo: "images/Githubpic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
A data enthusiast who explore datasets thouroughly and come up with valuable Insights using SQL,EXCEL,TABLEAU. I love learning  and exploring more about data analytics world. Let's connect on LinkedIn and talk about data. Happy to have you here!  
<br><br>
  <a href="https://www.linkedin.com/in/aksha-hrudhai/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
